targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            # Required: A name for the database and its path
            psycho_chat: lib/data/datasources/local/app_database.dart